### ISSUE TITLE
Model's trained weight not found

### ISSUE THREAD

**Issue by obinnadyke** [weitingchen83/JSTASR-DesnowNet-ECCV-2020#6]
Hi! I tried to download the A.h5 weight for modelparam folder but the 2 google-drive web links you provided cannot be found (i.e., open). Please can you provide a new link containing the trained weight. Thanks

**Comment by awhitewhale** [comment]
I have same issue.

**Comment by weitingchen83** [comment]
Hi, you can find in new url.
https://tinyurl.com/uvcu4vk
